Repository JECT-Study/Componote-FE, pull requests merged in 2024-12, with the labels that each got.

#2 [🔨chore]: ESLint 및 Prettier 기본 설정
  .eslintrc.js
  .eslintrc.json
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/app/page.tsx
  src/designToken/componoteSampleTokens.json
  tailwind.config.ts
  tsconfig.json
Labels: ⚙️chore, 👩🏻‍💻frontend

#3 [🔨chore]: 디자인 토큰 확정 파일 파싱 로직 구현
  src/app/page.tsx
  src/designToken/colorTokens(mode).json
  src/designToken/componoteSampleTokens.json
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#4 [🔨chore]: scheme 디자인토큰 적용
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#7 [🔨chore]: 컬러 토큰 camelCase -> kebab-case
  src/designToken/color-tokens(mode).json
  src/designToken/colorTokens(mode).json
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#8 [🔨chore]: storybook 설치
  .eslintrc.js
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/component/Badge/ComponentType.tsx
  src/component/Badge/Label.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: ⚙️chore, 👩🏻‍💻frontend

#9 [🐛fix]: storybook 오류 수정
  package-lock.json
  package.json
Labels: 🐛bug, 👩🏻‍💻frontend

#10 [🔨chore]: storybook에 tailwindCSS도 적용되도록 수정
  .storybook/main.ts
  .storybook/preview.ts
  src/component/Badge/ComponentType.tsx
  src/component/Badge/Label.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#11 [🔨chore]: figma 상의 gap 속성을 tailwind 상 spacing으로 변경
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#13 [🔨chore]: svgr 설치
  next.config.ts
  package-lock.json
  package.json
Labels: ⚙️chore, 👩🏻‍💻frontend

#14 [🔨chore]: styled-components 설치
  package-lock.json
  package.json
  src/app/component/page.tsx
  src/app/layout.tsx
  src/components/MyComponent/MyComponent.style.ts
  src/components/MyComponent/MyComponent.tsx
  src/components/index.ts
  src/styles/GlobalStyle.ts
  src/styles/Registry.tsx
Labels: ⚙️chore, 👩🏻‍💻frontend

#16 [🔨chore]: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 👩🏻‍💻frontend, 📃docs

#15 [✨feat]: Divider component 구현
  src/components/Divider/Divider.style.ts
  src/components/Divider/Divider.tsx
  src/components/index.ts
  src/stories/Divider.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#17 [🔨chore]: 디자인 시스템 tailwindCSS -> styled-components 마이그레이션
  .storybook/preview.ts
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/components/Divider/Divider.tsx
  src/components/MyComponent/MyComponent.style.ts
  src/components/index.ts
  src/styles/ClientComponentContainer.tsx
  src/styles/GlobalStyle.ts
  src/styles/Registry.tsx
  src/styles/theme.ts
  tailwind.config.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#18 [🐛fix]: storybook에서 ThemeProvider 적용 안되는 오류 수정
  .storybook/preview.ts
  .storybook/preview.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#19 [✨feat]: Logo component 구현
  public/logo/logo.svg
  public/logo/logo_icon.svg
  src/components/Divider/Divider.style.ts
  src/components/Logo/Logo.style.ts
  src/components/Logo/Logo.tsx
  src/components/index.ts
  src/stories/Logo.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 😓help wanted

#20 [🔨chore]: storybook에서 svgr 사용 가능하도록 설정
  .storybook/main.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#22 [✨feat]: 프로젝트에 사용되는 아이콘 일괄 저장
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/arrow-up.svg
  src/assets/icons/blank-line.svg
  src/assets/icons/bookmark-fill.svg
  src/assets/icons/bookmark-line.svg
  src/assets/icons/box-fill.svg
  src/assets/icons/box-line.svg
  src/assets/icons/chat-fill.svg
  src/assets/icons/chat-line.svg
  src/assets/icons/check-line.svg
  src/assets/icons/checkbox-blank-line.svg
  src/assets/icons/checkbox-fill.svg
  src/assets/icons/checkbox-line.svg
  src/assets/icons/chevron-down-line.svg
  src/assets/icons/chevron-left-line.svg
  src/assets/icons/chevron-right-line.svg
  src/assets/icons/chevron-up-line.svg
  src/assets/icons/close-circle-fill.svg
  src/assets/icons/close-circle-line.svg
  src/assets/icons/close-line.svg
  src/assets/icons/comment-1-line.svg
  src/assets/icons/comment-2-line.svg
  src/assets/icons/comment-3-line.svg
  src/assets/icons/corner-down-left-line.svg
  src/assets/icons/corner-down-right-line.svg
  src/assets/icons/equalizer-line.svg
  src/assets/icons/figma-line.svg
  src/assets/icons/filter-line.svg
  src/assets/icons/github-fill.svg
  src/assets/icons/heart-fill.svg
  src/assets/icons/heart-line.svg
  src/assets/icons/image-add-fill.svg
  src/assets/icons/image-add-line.svg
  src/assets/icons/moon-line.svg
  src/assets/icons/more-fill.svg
  src/assets/icons/more-line.svg
  src/assets/icons/reply-line.svg
  src/assets/icons/reset-left-line.svg
  src/assets/icons/search-line.svg
  src/assets/icons/skip-left-line.svg
  src/assets/icons/skip-right-line.svg
  src/assets/icons/sort-desc.svg
  src/assets/icons/storybook-fill.svg
  src/assets/icons/sun-line.svg
  src/assets/icons/zeroheight-fill.svg
  src/components/MyComponent/MyComponent.style.ts
  src/components/MyComponent/MyComponent.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#23 [✨feat]: Badge 배지 컴포넌트 구현
  .eslintrc.js
  src/components/Badge/Badge.ComponentType.style.ts
  src/components/Badge/Badge.ComponentType.tsx
  src/components/Badge/Badge.Label.style.ts
  src/components/Badge/Badge.Label.tsx
  src/components/Badge/Badge.style.ts
  src/components/Badge/Badge.tsx
  src/components/index.ts
  src/stories/Badge/Badge.ComponentType.stories.tsx
  src/stories/Badge/Badge.Label.stories.tsx
  src/stories/Badge/Badge.stories.tsx
  src/styles/theme.ts
Labels: ✨feature, 👩🏻‍💻frontend

#25 [✨feat]: shadow와 interaction 디자인 시스템 theme에 추가
  src/styles/theme.ts
Labels: ✨feature, 👩🏻‍💻frontend

#24 [✨feat]: toast component 구현
  src/app/component/page.tsx
  src/components/Toast/Toast.style.ts
  src/components/Toast/Toast.tsx
  src/components/index.ts
  src/stories/Toast.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#26 [♻️refactor]: 디자인 시스템 분리
  src/components/Badge/Badge.ComponentType.style.ts
  src/components/Badge/Badge.Label.style.ts
  src/components/Badge/Badge.style.ts
  src/components/Divider/Divider.style.ts
  src/components/Footer/Footer.style.ts
  src/components/Logo/Logo.style.ts
  src/components/Toast/Toast.style.ts
  src/styles/designSystem.tsx
  src/styles/theme.ts
Labels: 👩🏻‍💻frontend, 🪄refactor

#27 [✨feat]: Callout 콜아웃 컴포넌트 구현
  src/components/Callout/Callout.style.ts
  src/components/Callout/Callout.tsx
  src/components/index.ts
  src/stories/Badge/Badge.ComponentType.stories.tsx
  src/stories/Badge/Badge.Label.stories.tsx
  src/stories/Badge/Badge.stories.tsx
  src/stories/Callout/Callout.stories.tsx
  src/styles/designSystem.tsx
  src/styles/theme.ts
Labels: ✨feature, 👩🏻‍💻frontend

#28 [✨feat]: Interaction 컴포넌트 구현
  src/components/Interaction/Interaction.style.ts
  src/styles/designSystem.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#30 [✨feat]: chip component 구현
  .eslintrc.js
  src/app/component/page.tsx
  src/components/Chip/Chip.group.style.ts
  src/components/Chip/Chip.group.tsx
  src/components/Chip/Chip.style.tsx
  src/components/Chip/Chip.theme.ts
  src/components/Chip/Chip.tsx
  src/components/Chip/Chip.types.ts
  src/components/Chip/chipGroup.ts
  src/components/Footer/Footer.tsx
  src/components/Logo/Logo.style.ts
  src/components/Logo/Logo.tsx
  src/components/index.ts
  src/constants/messages.ts
  src/stories/Chip/Chip.group.stories.tsx
  src/stories/Chip/Chip.stories.tsx
  src/stories/Logo.stories.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#31 [✨feat]: IndexPanel 컴포넌트 구현
  src/components/IndexPanel/IndexPanel.style.ts
  src/components/IndexPanel/IndexPanel.tsx
  src/components/index.ts
  src/stories/IndexPanel.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#33 [✨feat]: button component 구현
  src/components/Button/Button.style.tsx
  src/components/Button/Button.theme.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/index.ts
  src/stories/Button.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend
