Repository JECT-Study/Componote-FE, pull requests merged in 2025-01, with the labels that each got.

#32 [✨feat]: Avatar 컴포넌트 구현
  .storybook/main.ts
  public/image/defaultAvatarImage.svg
  src/components/Avatar/Avatar.style.ts
  src/components/Avatar/Avatar.theme.ts
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Badge/Badge.ComponentType.style.ts
  src/components/Badge/Badge.ComponentType.tsx
  src/components/Badge/Badge.Label.style.ts
  src/components/Badge/Badge.Label.tsx
  src/components/Badge/Badge.style.ts
  src/components/Badge/Badge.theme.ts
  src/components/Badge/Badge.tsx
  src/components/Badge/Badge.types.ts
  src/components/Callout/Callout.Interactive.style.ts
  src/components/Callout/Callout.Interactive.tsx
  src/components/Callout/Callout.style.ts
  src/components/Callout/Callout.theme.ts
  src/components/Callout/Callout.tsx
  src/components/Callout/Callout.types.ts
  src/components/Footer/Footer.tsx
  src/components/index.ts
  src/constants/messages.ts
  src/stories/Avatar.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#35 [✨feat]: ContextMenu 컴포넌트 구현
  src/components/Badge/Badge.types.ts
  src/components/ContextMenu/Combobox.style.ts
  src/components/ContextMenu/Combobox.tsx
  src/components/ContextMenu/ContextMenu.style.ts
  src/components/ContextMenu/ContextMenu.theme.ts
  src/components/ContextMenu/ContextMenu.tsx
  src/components/ContextMenu/ContextMenu.types.ts
  src/components/ContextMenu/ContextMenuItem.style.ts
  src/components/ContextMenu/ContextMenuItem.tsx
  src/components/Interaction/Interaction.style.ts
  src/components/Interaction/Interaction.types.ts
  src/components/index.ts
  src/stories/ContextMenu/Combobox.stories.tsx
  src/stories/ContextMenu/ContextMenu.stories.tsx
  src/stories/ContextMenu/ContextMenuItem.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#36 [✨feat]: SocialAuth 관련 컴포넌트 구현
  src/assets/socialAuth/Github.svg
  src/assets/socialAuth/Google.svg
  src/components/SocialAuth/SocialAuthButton.style.ts
  src/components/SocialAuth/SocialAuthButton.tsx
  src/components/SocialAuth/SocialAuthIcon.style.ts
  src/components/index.ts
  src/stories/SocialAuthButton.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#37 [🐛fix]: focus 인터랙션 분리 (Button 태그에 focus 두번 잡히는 오류 수정)
  src/components/Button/Button.style.tsx
  src/components/Button/Button.tsx
  src/components/Interaction/Interaction.style.ts
  src/styles/designSystem.tsx
Labels: ✨feature, 🐛bug

#34 [✨feat]: InputField component 구현
  src/components/InputField/InputField.style.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputField.types.ts
  src/components/index.ts
  src/stories/Button.stories.tsx
  src/stories/InputField.stories.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#38 [✨feat]: navigationBar component 구현
  src/assets/logo/logo.svg
  src/assets/logo/logo_icon.svg
  src/components/Button/Button.tsx
  src/components/InputField/InputField.style.tsx
  src/components/InputField/InputField.tsx
  src/components/NavigationBar/NavItem.style.ts
  src/components/NavigationBar/NavItem.tsx
  src/components/NavigationBar/NavigationBar.style.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/components/NavigationBar/NavigationBar.types.ts
  src/components/index.ts
  src/constants/messages.ts
  src/stories/NavigationBar.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#39 [📝docs]: Fade 컴포넌트 deprecated / 임시 랜딩페이지 제작
  src/app/_components/Home.style.ts
  src/app/_components/HomeBanner.style.ts
  src/app/_components/HomeBanner.tsx
  src/app/page.tsx
  src/components/ContextMenu/Combobox.tsx
  src/components/ContextMenu/ContextMenu.tsx
  src/stories/Badge/Badge.ComponentType.stories.tsx
  src/stories/Badge/Badge.Label.stories.tsx
  src/stories/Badge/Badge.stories.tsx
  src/stories/Callout/Callout.Interactive.stories.tsx
  src/stories/Callout/Callout.stories.tsx
Labels: 👩🏻‍💻frontend, 📃docs

#40 [🐛fix]: Avatar 컴포넌트에 누락된 prop 추가
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Button/Button.tsx
  src/components/Callout/Callout.Interactive.tsx
  src/components/Chip/Chip.tsx
  src/components/IndexPanel/IndexPanel.tsx
  src/components/NavigationBar/NavItem.tsx
  src/components/SocialAuth/SocialAuthButton.tsx
  src/stories/Avatar.stories.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#45 [♻️refactor]: chip component $iconVisible prop 제거
  src/components/Chip/Chip.group.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/Chip.types.ts
  src/stories/Chip/Chip.stories.tsx
Labels: 👩🏻‍💻frontend, 🪄refactor

#43 [♻️refactor]: button component 불필요한 props 제거 및 스타일 속성 추가
  src/components/Button/Button.style.tsx
  src/components/Button/Button.theme.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/stories/Button.stories.tsx
Labels: 👩🏻‍💻frontend, 🪄refactor

#44 [♻️refactor]: input field component 수정
  src/components/InputField/InputField.style.tsx
  src/components/InputField/InputField.tsx
  src/components/InputField/InputField.types.ts
  src/stories/InputField.stories.tsx
Labels: 👩🏻‍💻frontend, 🪄refactor

#46 [✨feat]: banner component 구현
  public/image/accordion.png
  public/image/imageLayer.png
  src/app/_components/HomeBanner.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Banner/Banner.default.style.ts
  src/components/Banner/Banner.default.tsx
  src/components/Banner/Banner.document.style.ts
  src/components/Banner/Banner.document.tsx
  src/components/Banner/Banner.onboarding.style.ts
  src/components/Banner/Banner.onboarding.tsx
  src/components/Banner/Banner.profile.style.ts
  src/components/Banner/Banner.profile.tsx
  src/components/Banner/Banner.types.ts
  src/components/Callout/Callout.tsx
  src/components/Callout/Callout.types.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/components/index.ts
  src/constants/messages.ts
  src/stories/Banner/Banner.default.stories.tsx
  src/stories/Banner/Banner.document.stories.tsx
  src/stories/Banner/Banner.onboarding.stories.tsx
  src/stories/Banner/Banner.profile.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#48 [✨feat]: card component 구현
  public/image/sampleImage.png
  src/components/Badge/Badge.ComponentType.style.ts
  src/components/Button/Button.style.tsx
  src/components/Button/Button.types.ts
  src/components/Card/Card.component.style.tsx
  src/components/Card/Card.component.tsx
  src/components/Card/Card.designSystem.style.ts
  src/components/Card/Card.designSystem.tsx
  src/components/Card/Card.types.ts
  src/components/Card/CardInteraction.tsx
  src/components/Card/CardItem.style.ts
  src/components/Card/CardItem.tsx
  src/components/Chip/Chip.style.tsx
  src/components/Chip/Chip.types.ts
  src/components/Divider/Divider.style.ts
  src/components/InputField/InputField.style.tsx
  src/components/InputField/InputField.types.ts
  src/components/index.ts
  src/stories/Card/Card.component.stories.tsx
  src/stories/Card/Card.designSystem.stories.tsx
  src/stories/InputField.stories.tsx
  src/utils/IconWrapper.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#41 [✨feat]: Dialog 컴포넌트 제작
  README.md
  src/assets/images/dialogCompleteSampleImage.png
  src/assets/images/sampleImage.png
  src/components/Dialog/Dialog.Basic.style.ts
  src/components/Dialog/Dialog.Basic.tsx
  src/components/Dialog/Dialog.Complete.style.ts
  src/components/Dialog/Dialog.Complete.tsx
  src/components/Dialog/Dialog.EmailVerification.style.ts
  src/components/Dialog/Dialog.EmailVerification.tsx
  src/components/Dialog/Dialog.Login.style.ts
  src/components/Dialog/Dialog.Login.tsx
  src/components/Dialog/Dialog.Report.style.ts
  src/components/Dialog/Dialog.Report.tsx
  src/components/Dialog/Dialog.Verification.style.ts
  src/components/Dialog/Dialog.Verification.tsx
  src/components/Dialog/Dialog.style.ts
  src/components/Dialog/Dialog.tsx
  src/components/Divider/Divider.style.ts
  src/components/SocialAuth/SocialAuthButton.style.ts
  src/components/index.ts
  src/constants/messages.ts
  src/stories/Dialog.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#42 [✨feat]: 회원가입 페이지 UI 완성
  src/app/login/signin/_components/SignIn.style.ts
  src/app/login/signin/_components/SignInButton/SignInButton.style.ts
  src/app/login/signin/_components/SignInButton/SignInButton.tsx
  src/app/login/signin/_components/SignInFooter/SignInFooter.style.ts
  src/app/login/signin/_components/SignInFooter/SignInFooter.tsx
  src/app/login/signin/_components/SignInJob/SignInJob.style.ts
  src/app/login/signin/_components/SignInJob/SignInJob.tsx
  src/app/login/signin/_components/SignInProfile/SignInProfile.style.ts
  src/app/login/signin/_components/SignInProfile/SignInProfile.tsx
  src/app/login/signin/_components/SignInProfile/SignInProfileImage.style.ts
  src/app/login/signin/_components/SignInProfile/SignInProfileImage.tsx
  src/app/login/signin/_components/SignInProfile/SignInProfileNickname.style.ts
  src/app/login/signin/_components/SignInProfile/SignInProfileNickname.tsx
  src/app/login/signin/_components/SignInTitle/SignInTitle.style.ts
  src/app/login/signin/_components/SignInTitle/SignInTitle.tsx
  src/app/login/signin/page.tsx
  src/constants/chips.ts
  src/constants/messages.ts
Labels: ✨feature, 👩🏻‍💻frontend

#51 [✨feat]: onboarding page UI 구현
  public/image/onboarding.png
  src/app/_components/Home.style.ts
  src/app/_components/HomeBanner.style.ts
  src/app/_components/HomeBanner.tsx
  src/app/component/page.tsx
  src/app/page.tsx
  src/components/Banner/Banner.onboarding.style.ts
  src/components/Banner/Banner.onboarding.tsx
  src/components/Banner/Banner.types.ts
  src/components/Callout/Callout.style.ts
  src/components/Callout/Callout.tsx
  src/components/Callout/Callout.types.ts
  src/components/Logo/Logo.style.ts
  src/components/Logo/Logo.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Pages/Component/CardContainer.style.ts
  src/components/Pages/Component/CardContainer.tsx
  src/components/Pages/Onboarding/ImageContainer.style.ts
  src/components/Pages/Onboarding/ImageContainer.tsx
  src/components/Toolbar/Toolbar.tsx
  src/components/Toolbar/Toolbar.variant.tsx
  src/components/index.ts
  src/stories/Toolbar.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#52 [✨feat]: axios instance 설정 및 api end point 상수 처리
  .eslintrc.js
  package-lock.json
  package.json
  src/api/interceptor.ts
  src/constants/api.ts
Labels: ✨feature, 👩🏻‍💻frontend
