Repository JECT-Study/Componote-FE, pull requests merged in 2025-02, with the labels that each got.

#56 [✨feat]: empty state component 구현
  .eslintrc.js
  src/components/EmptyState/EmptyState.style.ts
  src/components/EmptyState/EmptyState.tsx
  src/components/EmptyState/EmptyState.type.ts
  src/components/index.ts
  src/stories/EmptyState.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#57 [✨feat]: pagination component 구현
  .eslintrc.js
  src/components/Pagination/Pagination.item.style.ts
  src/components/Pagination/Pagination.item.tsx
  src/components/Pagination/Pagination.style.ts
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/Pagination.types.ts
  src/components/Pagination/PaginationButton.tsx
  src/components/index.ts
  src/stories/Pagination.stories.tsx
  src/utils/paginationUtils.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#59 [✨feat]: feed component 구현
  src/components/Feed/Feed.mycomment.style.ts
  src/components/Feed/Feed.mycomment.tsx
  src/components/Feed/Feed.notification.style.ts
  src/components/Feed/Feed.notification.tsx
  src/components/Feed/Feed.types.ts
  src/components/index.ts
  src/stories/Feed/Feed.mycomment.stories.tsx
  src/stories/Feed/Feed.notification.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#60 [🔨chore]: Zustand 설치
  package-lock.json
  package.json
  src/app/page.tsx
  src/hooks/store/useLetterStore.ts
Labels: ⚙️chore, 👩🏻‍💻frontend

#61 [✨feat]: comment component 구현
  src/components/Button/Button.style.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/Comment/Comment.reply.style.ts
  src/components/Comment/Comment.reply.tsx
  src/components/Comment/Comment.style.ts
  src/components/Comment/Comment.tsx
  src/components/Comment/Comment.types.ts
  src/components/Comment/CommentInteraction.tsx
  src/components/Comment/UserSection.style.ts
  src/components/Comment/UserSection.tsx
  src/components/ContextMenu/ContextMenu.style.ts
  src/components/index.ts
  src/styles/GlobalStyle.ts
Labels: ✨feature, 👩🏻‍💻frontend

#62 [♻️refactor]: Login 로직 구현 및 관련 상태 관리
  src/api/userInfo.ts
  src/app/page.tsx
  src/components/Dialog/Dialog.Login.tsx
  src/hooks/api/useUserInfoQuery.ts
  src/hooks/store/useLetterStore.ts
  src/hooks/store/useSocialLoginStore.ts
  src/hooks/store/useTokenStore.ts
  src/hooks/store/useUserInfoStore.ts
  src/hooks/type/socialLoginProvider.types.ts
  src/types/user.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#66 [🐛fix]: Vercel 초기 배포에서 발견된 오류들 수정
  src/app/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Comment/Comment.reply.style.ts
  src/components/Comment/Comment.reply.tsx
  src/components/IndexPanel/IndexPanel.tsx
  src/components/Pages/Home/MainContent.tsx
  src/components/Pages/index.ts
  src/stories/Avatar.stories.tsx
  src/stories/Chip/Chip.group.stories.tsx
  src/stories/Dialog.stories.tsx
  src/stories/Tab.stories.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#53 [✨feat]: design system page UI 구현
  src/app/designsystem/page.tsx
  src/components/Chip/Chip.group.style.ts
  src/components/Layout/Layout.style.ts
  src/components/Pages/DesignSystem/DesignCardContainer.style.ts
  src/components/Pages/DesignSystem/DesignCardContainer.tsx
  src/components/index.ts
Labels: ✨feature, 👩🏻‍💻frontend

#63 [✨feat]: bookmark page UI 구현
  src/app/mybookmark/page.tsx
  src/components/EmptyState/EmptyState.style.ts
  src/components/Pages/Bookmark/MainContainer.style.ts
  src/components/Pages/Bookmark/MainContainer.tsx
  src/components/Pages/index.ts
  src/components/Toolbar/Toolbar.style.ts
  src/components/Toolbar/Toolbar.tsx
  src/constants/contextMenuLabels.ts
  src/constants/messages.ts
Labels: ✨feature, 👩🏻‍💻frontend

#64 [✨feat]: announce page UI 구현
  src/app/announce/page.tsx
  src/components/Comment/Comment.reply.tsx
  src/components/Pages/Announce/AnnounceContainer.style.ts
  src/components/Pages/Announce/AnnounceContainer.tsx
  src/components/Pages/Announce/AnnounceTab.style.ts
  src/components/Pages/Announce/AnnounceTab.tsx
  src/components/Pages/index.ts
  src/constants/messages.ts
Labels: ✨feature, 👩🏻‍💻frontend

#65 [✨feat]: my page UI 구현
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/components/Banner/Banner.profile.style.ts
  src/components/Pages/Profile/ProfileContainer.style.ts
  src/components/Pages/Profile/ProfileContainer.tsx
  src/components/Pages/Profile/ProfileTab.style.ts
  src/components/Pages/Profile/ProfileTab.tsx
  src/components/Pages/index.ts
Labels: ✨feature, 👩🏻‍💻frontend

#67 [🔨fix]: vercel 빌드 오류 해결
  src/app/designsystem/page.tsx
  src/components/Comment/Comment.types.ts
  src/constants/messages.ts
Labels: ✨feature, 👩🏻‍💻frontend

#68 [✨feat]: component detail page UI 구현
  src/app/component/[componentId]/page.tsx
  src/components/Banner/Banner.document.style.ts
  src/components/Banner/Banner.document.tsx
  src/components/Banner/Banner.types.ts
  src/components/Callout/Callout.style.ts
  src/components/Callout/Callout.theme.ts
  src/components/Callout/Callout.tsx
  src/components/Callout/Callout.types.ts
  src/components/Layout/Layout.style.ts
  src/components/Pages/ComponentDetail/DocumentSection.style.ts
  src/components/Pages/ComponentDetail/DocumentSection.tsx
  src/components/Pages/ComponentDetail/DocumentSection.types.ts
  src/components/Pages/index.ts
  src/constants/messages.ts
Labels: ✨feature, 👩🏻‍💻frontend

#71 [✨feat]: 회원가입시 닉네임 유효성 검사 로직 추가
  src/components/Pages/Signup/SignupButton/SignupButton.tsx
  src/components/Pages/Signup/SignupProfile/SignupProfileNickname.tsx
  src/utils/validateNickname.ts
Labels: ✨feature, 👩🏻‍💻frontend

#70 [✨feat]: component page component list 구현
  src/api/component.ts
  src/app/component/page.tsx
  src/components/Badge/Badge.ComponentType.tsx
  src/components/Badge/Badge.theme.ts
  src/components/Card/Card.component.tsx
  src/components/Card/Card.types.ts
  src/constants/api.ts
  src/constants/messages.ts
  src/hooks/api/common/useObserver.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
  src/stories/Badge/Badge.ComponentType.stories.tsx
  src/stories/Card/Card.component.stories.tsx
  src/types/component.ts
Labels: ✨feature, 👩🏻‍💻frontend

#72 [✨feat]: component detail page 세부 내용 표시
  src/api/componentDetail.ts
  src/app/component/[componentId]/page.tsx
  src/components/Banner/Banner.document.tsx
  src/components/Banner/Banner.types.ts
  src/components/Card/Card.component.style.tsx
  src/constants/messages.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
  src/hooks/api/componentDetail/useComponentDetailQuery.tsx
  src/stories/Banner/Banner.document.stories.tsx
  src/types/componentDetail.ts
Labels: ✨feature, 👩🏻‍💻frontend

#73 [✨feat]: component detail page 목차 바로 가기 구현
  src/app/component/[componentId]/page.tsx
  src/components/Banner/Banner.document.style.ts
  src/components/Banner/Banner.document.tsx
  src/components/IndexPanel/IndexPanel.style.ts
  src/components/IndexPanel/IndexPanel.tsx
  src/components/IndexPanel/IndexPanel.types.ts
  src/components/Pages/ComponentDetail/BannerContainer.style.ts
  src/components/Pages/ComponentDetail/BannerContainer.tsx
  src/components/Pages/ComponentDetail/ComponentDetail.types.ts
  src/components/Pages/ComponentDetail/DocumentArticle.tsx
  src/components/Pages/ComponentDetail/DocumentSection.style.ts
  src/components/Pages/ComponentDetail/DocumentSection.tsx
  src/components/Pages/ComponentDetail/DocumentSection.types.ts
  src/components/Pages/ComponentDetail/IndexPanelContainer.tsx
  src/components/Pages/ComponentDetail/IndexPannelContainer.style.ts
  src/components/Pages/index.ts
  src/stories/IndexPanel.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#75 [✨feat]: 디자인 시스템 리스트 불러오기 구현
  src/api/designSystem.ts
  src/api/signup.ts
  src/app/component/page.tsx
  src/app/designsystem/page.tsx
  src/components/Card/Card.designSystem.style.ts
  src/components/Card/Card.designSystem.tsx
  src/components/Chip/Chip.group.tsx
  src/components/Chip/Chip.types.ts
  src/components/Chip/chipGroup.ts
  src/components/Pages/DesignSystem/DesignSystemCards.tsx
  src/components/Pages/index.ts
  src/components/Toolbar/Toolbar.variant.tsx
  src/components/index.ts
  src/constants/api.ts
  src/constants/chipGroup.ts
  src/constants/designSystemFilterLabel.ts
  src/constants/messages.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
  src/hooks/api/componentDetail/useComponentDetailQuery.tsx
  src/hooks/api/designSystem/useDesignSystemInfiniteQuery.ts
  src/hooks/api/useAuthUrlQuery.ts
  src/hooks/api/useSignupMutation.ts
  src/hooks/api/useSocialLoginQuery.ts
  src/hooks/api/useUserInfoQuery.ts
  src/hooks/store/useUserInfoStore.ts
  src/stories/Card/Card.component.stories.tsx
  src/stories/Card/Card.designSystem.stories.tsx
  src/stories/Chip/Chip.group.stories.tsx
  src/types/api/component.ts
  src/types/api/componentDetail.ts
  src/types/api/designSystem.ts
  src/types/api/login.ts
  src/types/api/user.ts
  src/types/enum/designSystemFilters.ts
Labels: ✨feature, 👩🏻‍💻frontend

#76 [✨feat]: component page 정렬 구현
  src/app/component/page.tsx
  src/app/mybookmark/page.tsx
  src/components/Toolbar/Toolbar.tsx
  src/components/Toolbar/Toolbar.variant.tsx
  src/constants/componentChip.ts
  src/constants/componentFilter.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
  src/store/common/useContextMenuStore.ts
  src/store/component/useChipStore.ts
  src/types/enum/componentFilter.ts
Labels: ✨feature, 👩🏻‍💻frontend

#77 [👽fix]: component list API 변경에 따른 수정
  src/api/component.ts
  src/app/component/page.tsx
  src/constants/api.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
Labels: ✨feature, 👩🏻‍💻frontend

#78 [✨feat]: navigation bar component 검색 구현
  src/api/component.ts
  src/components/ContextMenu/Combobox.style.ts
  src/components/ContextMenu/ContextMenuItem.style.ts
  src/components/InputField/InputField.style.tsx
  src/components/InputField/InputField.tsx
  src/components/NavigationBar/NavigationBar.style.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/constants/api.ts
  src/hooks/api/component/useComponentListInfiniteQuery.ts
  src/hooks/api/component/useSearchComponentInfiniteQuery.ts
  src/store/common/useComboBoxStore.ts
  src/store/common/useSearchStore.ts
  src/types/api/component.ts
  src/utils/extractKorean.ts
Labels: ✨feature, 👩🏻‍💻frontend

#79 [♻️refactor]: 로그인 관련 API 수정된 것 반영
  src/api/login.ts
  src/api/signup.ts
  src/components/Pages/Home/MainContent.tsx
  src/components/Pages/Signup/SignupButton/SignupButton.tsx
  src/hooks/api/useLoginMutation.ts
  src/hooks/store/useSignupUserStore.ts
  src/types/api/login.ts
  src/types/api/user.ts
Labels: 👩🏻‍💻frontend, 🪄refactor

#80 [✨feat]: design system page 목록 미구현 항목 추가 구현
  src/app/designsystem/page.tsx
  src/components/Card/Card.designSystem.style.ts
  src/components/Card/Card.designSystem.tsx
  src/components/Card/Card.types.ts
  src/components/Pages/DesignSystem/DesignSystemCards.tsx
  src/stories/Card/Card.designSystem.stories.tsx
  src/types/api/component.ts
  src/types/api/designSystem.ts
  src/types/common/pageData.ts
Labels: ✨feature, 👩🏻‍💻frontend

#81 [✨feat]: design system page 정렬 구현
  src/app/designsystem/page.tsx
  src/components/Pages/DesignSystem/DesignSystemCards.tsx
  src/constants/contextMenuLabels.ts
  src/constants/designSystemFilterLabel.ts
  src/hooks/api/designSystem/useDesignSystemInfiniteQuery.ts
  src/types/enum/componentFilter.ts
  src/types/enum/designSystemFilters.ts
Labels: ✨feature, 👩🏻‍💻frontend

#82 [✨feat]: 프로필 편집 기능 구현
  .prettierrc
  src/api/userInfo.ts
  src/app/component/page.tsx
  src/app/login/signup/page.tsx
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/components/Banner/Banner.profile.tsx
  src/components/Banner/Banner.types.ts
  src/components/InputField/InputField.tsx
  src/components/InputField/InputField.types.ts
  src/components/NavigationBar/NavigationBar.style.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/components/Pages/Profile/Edit/ProfileEdit.style.ts
  src/components/Pages/Profile/Edit/ProfileEditBodyModuleWrapper.tsx
  src/components/Pages/Profile/Edit/ProfileEditButton/ProfileEditButton.style.ts
  src/components/Pages/Profile/Edit/ProfileEditButton/ProfileEditButton.tsx
  src/components/Pages/Profile/Edit/ProfileEditJob/ProfileEditJob.style.ts
  src/components/Pages/Profile/Edit/ProfileEditJob/ProfileEditJob.tsx
  src/components/Pages/Profile/Edit/ProfileEditModuleWrapper.tsx
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfile.style.ts
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfile.tsx
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfileImage.style.ts
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfileImage.tsx
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfileNickname.style.ts
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfileNickname.tsx
  src/components/Pages/Profile/Edit/ProfileEditWrapper.tsx
  src/components/Pages/Signup/SignupButton/SignupButton.tsx
  src/components/Pages/Signup/SignupTitle/SignupTitle.tsx
  src/components/Pages/index.ts
  src/constants/api.ts
  src/constants/messages.ts
  src/hooks/api/profileEdit/useProfileEditMutation.ts
  src/hooks/store/useProfileEditStore.ts
  src/hooks/store/useTokenStore.ts
  src/hooks/store/useUserInfoStore.ts
  src/stories/Banner/Banner.profile.stories.tsx
  src/types/api/user.ts
  src/utils/getJobKey.ts
Labels: ✨feature, 👩🏻‍💻frontend

#83 [♻️refactor]: store 위치 변경
  src/app/component/page.tsx
  src/app/designsystem/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/Banner/Banner.profile.tsx
  src/components/Dialog/Dialog.Login.tsx
  src/components/Pages/Home/MainContent.tsx
  src/components/Pages/Profile/Edit/ProfileEditButton/ProfileEditButton.tsx
  src/components/Pages/Profile/Edit/ProfileEditJob/ProfileEditJob.tsx
  src/components/Pages/Profile/Edit/ProfileEditProfile/ProfileEditProfileNickname.tsx
  src/components/Pages/Signup/SignupButton/SignupButton.tsx
  src/components/Pages/Signup/SignupJob/SignupJob.tsx
  src/components/Pages/Signup/SignupProfile/SignupProfileNickname.tsx
  src/hooks/api/useLoginMutation.ts
  src/hooks/api/useSignupMutation.ts
  src/store/user/useProfileEditStore.ts
  src/store/user/useSignupUserStore.ts
  src/store/user/useSocialLoginStore.ts
  src/store/user/useTokenStore.ts
  src/store/user/useUserInfoStore.ts
Labels: 👩🏻‍💻frontend, 🪄refactor

#84 [✨feat]: 디자인 시스템 페이지 필터 기능 구현
  src/api/designSystem.ts
  src/app/designsystem/page.tsx
  src/components/Chip/Chip.group.tsx
  src/components/Toolbar/Toolbar.tsx
  src/constants/api.ts
  src/hooks/api/designSystem/useDesignSystemInfiniteQuery.ts
  src/store/designSystem/useDesignSystemFilterStore.ts
  src/types/enum/designSystemFilters.ts
Labels: ✨feature, 👩🏻‍💻frontend

#85 [♻️refactor]: 상단바 isAuthorized prop 제거
  src/app/announce/page.tsx
  src/app/component/[componentId]/page.tsx
  src/app/component/page.tsx
  src/app/designsystem/page.tsx
  src/app/mybookmark/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/components/NavigationBar/NavigationBar.types.ts
Labels: 👩🏻‍💻frontend, 🪄refactor

#86 [✨feat]: 상단바의 Avatar 클릭시 context Menu 구현
  src/components/NavigationBar/NavigationBar.style.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/constants/contextMenuLabels.ts
Labels: ✨feature, 👩🏻‍💻frontend

#88 [🐛fix]: 프로필 편집 후 프로필 페이지에 userInfo 바로 업데이트
  src/hooks/api/profileEdit/useProfileEditMutation.ts
Labels: 🐛bug, 👩🏻‍💻frontend

#87 [✨feat]: design system 검색 구현
  src/api/designSystem.ts
  src/components/ContextMenu/ContextMenuItem.style.ts
  src/components/NavigationBar/NavigationBar.tsx
  src/constants/api.ts
  src/hooks/api/designSystem/useSearchDesignSystemInfiniteQuery.ts
  src/types/api/designSystem.ts
Labels: ✨feature, 👩🏻‍💻frontend

#89 [🔨fix]: 로그인하지 않았을 때 프로필이 표시되는 버그 수정
  src/components/NavigationBar/NavigationBar.tsx
Labels: 🐛bug, 👩🏻‍💻frontend
